### ISSUE TITLE
The library file isn't in Creitive\Breadcrumbs

### ISSUE THREAD

**Issue by mahmutbayri** [creitive/laravel5-breadcrumbs#1]

**Comment by levacic** [comment]
What do you mean? Are you talking about [this class](https://github.com/creitive/breadcrumbs/blob/master/src/Creitive/Breadcrumbs/Breadcrumbs.php)?

If so, that's intentional; the core breadcrumbs library is in its own `creitive/breadcrumbs` package, which is [listed as a dependency](https://github.com/creitive/laravel5-breadcrumbs/blob/5b08d54e518bbb3afc3dffba34934240eb9e8c43/composer.json#L18) in this package's `composer.json` file - this means that it will automatically be installed by Composer when this package is installed, so it will nonetheless be available in your code.

This package only provides integration with Laravel 5 - there is also the `creitive/laravel4-breadcrumbs` package that provides Laravel 4 integration. Both that package and this one use the same core library (which is framework-agnostic).

Is something not working correctly for you? I've just tried to install this library in a fresh Laravel 5 app, and everything worked as expected.

**Comment by levacic** [comment]
Since you haven't responded in two weeks, and I'm fairly certain that this package works as it should, I'll go ahead and close this issue. If you still think you have a problem, feel free to reopen it, but please add some additional information, so that we can figure out what's going on.
