### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by HasanAlyazidi** [creitive/laravel5-breadcrumbs#7]
Hello

laravel5-breadcrumbs does not support Laravel 6, Can you update the package please?

![image](https://user-images.githubusercontent.com/7901330/64253168-f7817080-cf1c-11e9-8e3f-d2e0030a8ff1.png)

Thank you for your time and effort,

**Comment by it-can** [comment]
@levacic can you update this package to Laravel 6?

**Comment by levacic** [comment]
Seeing as this package is called `laravel5-breadcrumbs`, it feels kinda _wrong_ for it to support Laravel 6. How about if we release another `laravel6-breadcrumbs` package instead? Would that work for you?

**Comment by it-can** [comment]
no problem...

**Comment by levacic** [comment]
Okay, please check out https://github.com/creitive/laravel6-breadcrumbs and let me know if you have any issues with it.

It works exactly the same in terms of configuration and usage, it's just a different package that supports Laravel 6.

**Comment by it-can** [comment]
I think that

```
"illuminate/support": "~6.0"
```

needs to be

```
"illuminate/support": "^6.0"
```

**Comment by it-can** [comment]
added a PR https://github.com/creitive/laravel6-breadcrumbs/pull/1

**Comment by levacic** [comment]
Both should work, the difference is if a patch version is supplied as well, for example:

- `~6.0` is equivalent to `>=6.0 <7.0`
- `^6.0` is equivalent to `>=6.0 <7.0`
- `~6.0.0` is equivalent to `>=6.0.0 <6.1.0`
- `^6.0.0` is equivalent to `>=6.0.0 <7.0.0`

As you can see, it should work the same because we don't specify the patch in the version constraint. Does it not work for you for some reason?

See the following for more info:

- https://getcomposer.org/doc/articles/versions.md#tilde-version-range- 
- https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by it-can** [comment]
aah ok, no problem then...

**Comment by levacic** [comment]
Okay, so then let us know and please confirm if it works for you - I've tried it and it seems to be fine, but just in case your project is setup differently somehow...

Also, thank you both for the reminder! @HasanAlyazidi @it-can

**Comment by it-can** [comment]
yeah works fine! thanks
